### ISSUE TITLE
num argument name rounding / round

### ISSUE THREAD

**Issue by c-ortbauer** [Mc-Zen/zero#4]
Hi 
In the documentation the argument name for the rounding settings is **rounding** 

![image](https://github.com/user-attachments/assets/4c5758dc-761e-46f9-ab17-2b9cb8fcd948)

As this was not working for me, I tried **round** and it works.

`#num("12.3456789", digits:3, round:(mode:"places",precision:3))`

**Comment by Mc-Zen** [comment]
Oh, my bad!
